name: AIKO
description: Lynn ist dein digitaler Freund zum Plaudern und Lernen!

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

#from here to the end copy the code and replace it with your previous code (version 3.7.2)

version: 3.8.1+38

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  location: ^5.0.3
  video_player: ^2.7.2
  lottie: ^2.6.0
  rive: ^0.11.17
  shared_preferences: ^2.2.1  # Fügen Sie die neueste Version hinzu. Überprüfen Sie https://pub.dev/packages/shared_preferences für die neueste Version.
  animated_text_kit: ^4.2.2
  xml: ^6.3.0
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  get: ^4.6.6
  flutter_svg: 2.0.7
  http: ^1.1.0
  get_storage: 2.1.1
  flutter_spinkit: 5.2.0
  speech_to_text: 6.3.0
  flutter_tts: ^3.8.1
  firebase_auth: ^4.10.1
  #  google_mobile_ads:
  google_sign_in: ^6.1.5
  the_apple_sign_in: ^1.1.1
  saver_gallery: ^2.0.1
  permission_handler: ^10.4.3
  device_info_plus: ^9.0.3
  dio: 5.3.2
  share_plus: 7.1.0
  cloud_firestore: ^4.9.3
  webview_flutter: 4.2.4
  http_auth: 1.0.3
  flutter_stripe: ^9.3.0
  firebase_messaging: ^14.6.9
  flutter_local_notifications: ^15.1.1
  modal_progress_hud_nsn: 0.4.0
  firebase_storage: ^11.2.8
  image_picker: ^1.0.4
  flutter_sslcommerz: ^2.2.2-nullsafety.0
  pay: ^1.1.2
  unity_ads_plugin: ^0.3.8

  font_awesome_flutter: ^10.5.0
  flutter_paystack:
    git:
      url: https://github.com/appdevsx/flutter_paystack
      ref: master
  flutterwave_standard: 1.0.8
  uuid: 
  syncfusion_flutter_pdf:
  syncfusion_flutter_pdfviewer: 22.2.11
  path_provider: ^2.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  flutter_rename_app_plus3: ^1.2.1

  #  change_app_package_name: ^1.1.0
  #  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.13.1
  # flutter_app_name:
  #  name: "AIKO"   # >> Set AppName First

flutter_rename_app_plus:
  application_name: AIKO
  dart_package_name: aiko
  application_id: com.tech.aiko
  bundle_id: com.tech.aiko
  android_package_name: com.tech.aiko
  ios_bundle_name: AIKO


dependency_overrides:
  webview_flutter: ^4.2.4
  http: 1.1.0


flutter:
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
  uses-material-design: true

  assets:
    - assets/
    - assets/logo/bot.png
    - assets/logo/bot2.png
    - assets/apple_pay.json
    - assets/google_pay.json
    - assets/icon/
    - assets/icon/diet_chart.svg
    - assets/heart.json
flutter_icons:
  android: true
  ios: true
  image_path: "android/app/src/main/res/drawable/launch_image.png"


#end version 3.7.2